name: Latest Medium posts

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@venomtechofficial"
          max_post_count: 5
          template: "- 📝 [$title]($url) <sub>· $date</sub>$newline"
          date_format: "mmm d, yyyy"
